Flight package
PresearchOfficial/presearch-packages pull request #158
Opened 2022-08-24 00:15 UTC by piwnik

Flight package

![FlightPackageResponsive](https://user-images.githubusercontent.com/3851067/186287671-91cba5fb-0342-4ddc-b6e0-67000c699d02.gif)

2022-08-25 20:39 UTC, treygrainger commented
Thanks, @piwnik - we'll take a look soon!

2022-08-28 17:52 UTC, piwnik commented
Flight progress visualization

![image](https://user-images.githubusercontent.com/3851067/187087864-79dd80ed-ba5e-45d9-aab4-52d4d885f491.png)

2022-08-30 11:41 UTC, jejopl requested changes
What do you think about using a different colors depends on the flight status?
Green - complete
Bluish - in progress
Orange - when there was a delay

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/32012330/187427285-0d83c2af-a4ad-4b70-8da2-5cfa1b79b7ec.png">


--------
Also, one more thing about the API. For me, it have a pretty long response time, sometimes up to 5 seconds. Are you good to switch to a different API provider? The package will timeout when there will be no response for 1500ms on production

2022-08-30 11:41 UTC, jejopl commented on packages/flight/index.js
> +        const flights = data.data;
We need to catch request error here 
```suggestion
        const request = await axios.get(flightUrl, {
            params: {
                "access_key": API_KEY,
                "flight_iata": flightNo
            }
        }).catch(error => ({ error });;

        if (request.error) {
            return null;
        }
        const flights = request.data.data;
```

2022-08-30 14:02 UTC, piwnik commented on packages/flight/index.js
> +            cursor: pointer;
done

2022-08-30 14:04 UTC, piwnik commented
Not sure if colored as you imagined. Misunderstood?

![FlightPackageColorfull](https://user-images.githubusercontent.com/3851067/187457610-f2ed1c72-1900-4b11-a00f-b17f9508c795.gif)

2022-08-30 14:08 UTC, piwnik commented on packages/flight/index.js
> +        const flights = data.data;
Code is inside try/catch block which will catch error if such.

2022-08-30 14:10 UTC, piwnik commented
What about API - will try to find other provider.

2022-08-30 23:50 UTC, piwnik commented
Changed API provider to [flightaware](https://flightaware.com). Now more past/scheduled flight can be displayed. Currently displaying yesterday/today/tomorrow. Hope flightaware will be faster.

2022-08-31 08:51 UTC, jejopl commented
Great, thanks @piwnik! Awesome job. I'll review it when I will have a moment

2022-09-01 08:58 UTC, jejopl commented
Hey @piwnik, are you able to send the API key that you've used to jeremiasz@presearch.io? I'm having some troubles with getting the key from flightaware. I want to use it for testing before we will purchase the API

2022-09-01 12:35 UTC, piwnik commented
> Hey @piwnik, are you able to send the API key that you've used to [jeremiasz@presearch.io](mailto:jeremiasz@presearch.io)?

@jejopl Sent.

2022-09-02 09:06 UTC, jejopl requested changes

2022-09-02 09:06 UTC, jejopl commented on packages/flight/index.js
> +        console.error(error);
Currently, we are not logging errors from inside of the package. So this will create a lot of noise inside node console and we don't want that. So for now, I suggest to remove this console.error()
```suggestion
```

2022-09-02 09:06 UTC, jejopl commented on packages/flight/index.js
> +    const regexString = new RegExp(/^flight ([a-zA-Z]{2,3}\d{1,4})$/);
It looks like that the regex is not working for some of the flights, i. e. "flight QTR76R"

2022-09-02 10:08 UTC, piwnik commented on packages/flight/index.js
> +        console.error(error);
Removed error logging.

2022-09-02 10:08 UTC, piwnik commented on packages/flight/index.js
> +    const regexString = new RegExp(/^flight ([a-zA-Z]{2,3}\d{1,4})$/);
Added optional following character.

2022-09-02 11:35 UTC, jejopl commented
Great job @piwnik, everything works great! One small thing - maybe it will be good to add the timezone to the Departure/Arrival fields? Or maybe `Current Time` field? 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/32012330/188130847-5fe48329-0fa3-4d93-84fd-f0ba3618020a.png">

2022-09-02 12:03 UTC, piwnik commented
> everything works great! One small thing - maybe it will be good to add the timezone to the Departure/Arrival fields? Or maybe `Current Time` field?

Not sure what you mean. Time under departure/arrival is displayed as local time in that airport timezone. You think about additionally display user (which runs query) time? For example if departure time in Norway/Oslo is 1:15 PM and user runs query from Canada/Toronto, then additionally Canada/Toronto time 7:15 AM should also be displayed to user? And then two times will be displayed one under another? (and probably clarifying labels also are needed)

2022-09-02 13:29 UTC, jejopl commented
Hmm, yeah, something to make it clear. Some people may think that it's their local time and not the airport time. 
What do you think?

2022-09-02 14:25 UTC, jejopl commented
@piwnik, actually I was speaking with the team members and they said that that's the standard. So, I think that we are good - there's no need to change

2022-09-05 13:21 UTC, piwnik commented
> So, I think that we are good - there's no need to change

@jejopl, is anything more left to improve/change then?

2022-09-08 09:59 UTC, jejopl commented
Sorry @piwnik, missed your message. It's all good. We are in the process of getting the API key for production

2022-10-20 11:09 UTC, merged