Feature/OpenSea: Create OpenSea package
PresearchOfficial/presearch-packages pull request #79
Opened 2021-09-07 22:28 UTC by dieudonneAwa

2021-09-11 14:26 UTC, treygrainger requested changes
Hi @dieudonneAwa, thanks for putting this package together! I've added comments throughout the PR with requested changes. If you have any questions, feel free to ask!

All the best,

-Trey

2021-09-11 14:26 UTC, treygrainger commented on packages/OpenSea/index.js
> +                  keyboard_arrow_right
This "keyboard_arrow_right" text is rendering directly since the styles weren't added to the package and were added to the demo page instead. Please ensure any needed styles get moved into this package (not an external reference) so it's self-contained. Thanks!

![image](https://user-images.githubusercontent.com/1043085/132950578-dd0d4e5d-201c-4543-9dde-8b9d06ef845a.png)

2021-09-11 14:26 UTC, treygrainger commented on packages/OpenSea/index.js
> +    <div style="max-width: 500px;" class="mx-2 rounded flex flex-column container-fluid bg-cultured">
I don't think we're going to be able to really display more than one of these unless the other ones are way smaller and organized. I'd suggest maybe only showing the first one, and then if there are more than one have a "See more >" link of some sort. This is what is currently looks like, for reference:

![image](https://user-images.githubusercontent.com/1043085/132950592-461b2e22-ee80-4171-bc5e-fab83b72b978.png)

2021-09-11 14:26 UTC, treygrainger commented on packages/OpenSea/index.js
> +          Owned by &nbsp; <a class="text-bluetiful" href="${
The "owned by" is always showing up as "Address" for me, which looks a little strange since we know the owning address and are linking to it. I think we should show the actual address instead, or possibly a shortened version to save space (i.e. 0xXXXX...XXXX)

2021-09-11 14:26 UTC, treygrainger commented on packages/OpenSea/index.js
> +  const assets = await loadAssets(query);
This is running the API calls to OpenSea for every single search request, which we absolutely cannot do. The purpose of the trigger is to have a small, light-weight check to verify whether we should invoke the package at all. In this case, the trigger is currently hitting the opensea API twice for every query (i.e. "shoes") just to check if it's an address with an NFT. Then it later hits the opensea API again during processing another 2 times.

The trigger function needs to be replaces by something that validates whether the query could trigger the package. In this case, you probably want a light-weight Regex that matches all valid contract addresses across the various blockchains that could hold NFTs.

We definitely can't be hitting APIs in the trigger, though.

2021-09-11 14:26 UTC, treygrainger commented on packages/OpenSea/index.js
> +        ((asset.owner && asset.owner.address === query) ||
Same question as above as to whether the payout address and creator.address are redundant given the actual API checks only checking the other two.

2021-09-11 14:26 UTC, treygrainger commented on packages/OpenSea/index.js
> +module.exports = { OpenSea, trigger };
will be "openSea" after you rename function

2021-09-11 14:26 UTC, treygrainger commented on packages/OpenSea/package.json
> +  "main": "index.ts",
Should be index.js and not index.ts

2021-09-11 14:26 UTC, treygrainger commented on server/index.js
> +  console.log(packageObject);
Remove this. Looks like it was added during debugging.

2021-09-11 14:26 UTC, treygrainger commented on server/index.js
> +        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
Can't import styles like this here for a a few reasons:
1) This is just a demo page so you can see what a package will render like. Any styles added to the demo page and not the package itself won't apply to the package, making it just look good on the demo page and not when the actual package is rendered in production.
2) All packages need to have self-contained styles. Applying global styles can impact the rendering of all packages.
3) We can't link the third-party files like this anyway, as it allows third parties to track users. In this case, Google and jsdelivr.net could both track our users if we link external files like this in the package.

So TLDR; we need to keep this index.js page free from any styles that would make it look different than production, need to ensure each package's styles are self-contained within the package, and need to ensure we're not linking to any files that would require a user's web browser to hit a third-party website.

2021-09-13 19:44 UTC, dieudonneAwa commented on packages/OpenSea/index.js
> +          (asset.collection && asset.collection.payout_address === query) ||
Yes @treygrainger 
You're right about the checks on collection.payout_address and asset.creator addresses, they are not necessary. I will remove them at once.

2021-10-30 13:24 UTC, jejopl commented
@dieudonneAwa I've moved this PR to #88
Let me know if everything is okay and I will merge it

2021-10-31 10:02 UTC, dieudonneAwa commented
> @dieudonneAwa I've moved this PR to #88 Let me know if everything is okay and I will merge it

All okay I think.

2021-11-04 10:20 UTC, closed without merging